environment:
  matrix:
    - GENERATOR: "Visual Studio 14"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14"
      CONFIG: Release

    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Release

    - GENERATOR: "Visual Studio 15"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 15"
      CONFIG: Release

    - GENERATOR: "Visual Studio 15 Win64"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 15 Win64"
      CONFIG: Release
build_script:
  - cmake "-G%GENERATOR%" -H. -B_builds
  - cmake --build _builds --config "%CONFIG%"